## Numpy

### 1. Numpy Array and Operation

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

< numpy.array 의 특징 >
1. 모든 원소의 dtype이 같다.
2. 연산의 의미가 조금 다르다. (broadcasting)
3. 대용량 array 인 경우에 for문을 직접 사용하는 것보다 내부적으로 정의된 연산을 사용하는게 더 빠르다.
4. 생성 후에 크기 변경이 불가능합니다.(원소는 바꿀 수 있다.)

### 1.1. Numpy Array creation

In [ ]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [ ]:
#np.__version__

'1.25.2'

In [ ]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4]

In [ ]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [[1, 2],
         [3, 4]]

In [ ]:
# 파이썬 list를 numpy array로 변환합니다.

# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
np.array(data)

array([1, 2, 3, 4])

In [ ]:
# 2차원 리스트를 np.array로 만듭니다.
arr2 = np.array(data2) # data2라는 리스트를 numpy array로 만들어라.
arr2.shape

(2, 2)

In [ ]:
# 0부터 9까지 숫자를 자동으로 생성한 array
np.arange(0, 10).shape #(10, )
np.zeros(shape=(5, 3, 4))
np.linspace(0, 1, 100) # [start, stop]에서 number를 균등한 구간으로 잘라서 원소를 생성.
np.random.randn(5, 3)  # 주어진 shape을 가지는 numpy array 를 만들어주는데, 원소는 표준정규분포에서 sampling.

array([[-0.89868307, -0.05745324,  0.79060594],
       [-1.22957092,  0.67825389,  0.71189405],
       [ 1.85515739, -0.06538827,  0.26570045],
       [-0.49113245, -0.85397007, -0.48243132],
       [-0.6219323 ,  0.30376292, -1.24048611]])

In [ ]:
# 10부터 99까지 숫자를 자동으로 생성한 array


### 1.2. Reshaping array

In [ ]:
# 3 x 3 행렬을 만들어봅시다.
# 1차원: vector
# 2차원: martix
# 3차원 이상: temsor
# shape은 가장 바깥 괄호부터 원소의 개수를 순차적으로 기록한 것으로 정의/
x = np.zeros(shape=(5,3, 4))

# 224 x 224 크기의
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# reshape을 이용하여 만들어봅시다.
x = np.arange(1, 10).reshape(3, 3)
#x = np.arange(1, 10).reshape(2, 4)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x = np.arange(1, 10).reshape(9, 1) # (9, ) != (9, 1)
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
# x = np.arange(1, 121).reshape(24, -1) # 계산하기 어려울 땐 -1, 약수가 아닌 '7'같은건 안됨.
x = np.arange(1, 121).reshape(-1, 4, 2)
x

array([[[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12],
        [ 13,  14],
        [ 15,  16]],

       [[ 17,  18],
        [ 19,  20],
        [ 21,  22],
        [ 23,  24]],

       [[ 25,  26],
        [ 27,  28],
        [ 29,  30],
        [ 31,  32]],

       [[ 33,  34],
        [ 35,  36],
        [ 37,  38],
        [ 39,  40]],

       [[ 41,  42],
        [ 43,  44],
        [ 45,  46],
        [ 47,  48]],

       [[ 49,  50],
        [ 51,  52],
        [ 53,  54],
        [ 55,  56]],

       [[ 57,  58],
        [ 59,  60],
        [ 61,  62],
        [ 63,  64]],

       [[ 65,  66],
        [ 67,  68],
        [ 69,  70],
        [ 71,  72]],

       [[ 73,  74],
        [ 75,  76],
        [ 77,  78],
        [ 79,  80]],

       [[ 81,  82],
        [ 83,  84],
        [ 85,  86],
        [ 87,  88]],

       [[ 89,  90],
        [ 91,  92],
        [ 93,  94],
        [ 95,  96]],

       [[ 97,  9

In [ ]:
# row vector를 column vector로


In [ ]:
# 펼치기


### 1.3. Concatenation of arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1 + arr2 = ?

# arr1와 arr2를 합칩니다
arr1 + arr2

array([5, 7, 9])

In [ ]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# stacking horizontally
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

## 1.4. Array Arithmetic (like vector) --> Universal Function

In [ ]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기. # 원소끼리 계산함.
v1 = np.array((1, 2, 3))
v2 = np.array((4, 5, 6))

In [ ]:
# 리스트로 더하기 연산해보기
v1 + v1

array([2, 4, 6])

In [ ]:
#  vector addition


In [ ]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [ ]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [ ]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [ ]:
# dot product (곱한 후 더한 값)
v1 @ v2

32

### 1.5. Broadcast and Universal Function

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [ ]:
arr1 = np.array([1, 2, 3])

In [ ]:
# arr2 = np.array([-1, -1, -1])
# arr2 = np.array([-1, -1, -1, -1])
arr2 = np.array(([-1, -1, -1],
                [1, 1, 1]))

In [ ]:
# 2개의 array를 더해보면?
# arr1 + arr2 # 2->2->3(v)
arr1 + arr2 # (3, ) + (2, 3) 크기가 매칭되는 것을 찾아서 연산 (3, ) + (3, 2)는 안됨
# (3, ) + (3, 4, 5) (v)
# (3, 4) + (5, 4, 3) (v)
# (3, 4) + (3, 4, 5) (x)

array([[0, 1, 2],
       [2, 3, 4]])

In [ ]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[-1, -2, -3],
       [ 1,  2,  3]])

- Universal Function : broadcast 기능을 확장해서, numpy array의 모든 원소에 동일한 함수를 반복문으로 적용한 것과 같은 효과를 내는 기능.

In [ ]:
# f = lambda x : 1/x
arr1 / 1 ## int -> float

## Universal Function
1 / arr1 ## 각 원소를 reverse 연산.

def reverse_num(x):
  return 1/x
for i in range(len(arr1)):
  arr1[i] = reverse_num(arr1[i])

In [ ]:
# f = lambda x : x + 2


### 1.6. Indexing
Pandas에서 배울 예정

In [ ]:
arr1 = np.arange(10)

In [ ]:
# 첫번째 원소


In [ ]:
# 마지막 원소


In [ ]:
# 앞에서부터 원소 3개 slicing


In [ ]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

In [ ]:
# arr2의 2row, 3column 원소 = 7


In [ ]:
# arr2의 세번째 column [3, 7, 11]


In [ ]:
# arr2의 두번째 row


## 2. Numpy Methods

- numpy에서 사용되는 여러가지 함수들을 사용해봅시다.

### 2.1. Math Functions

In [ ]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
# pseudo-random : 현재 시각(ns)
np.random.seed(42) # set send number
mat1 = np.random.randn(5, 3)
mat1

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [ ]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[0.49671415, 0.1382643 , 0.64768854],
       [1.52302986, 0.23415337, 0.23413696],
       [1.57921282, 0.76743473, 0.46947439],
       [0.54256004, 0.46341769, 0.46572975],
       [0.24196227, 1.91328024, 1.72491783]])

In [ ]:
# mat1 제곱하기
np.square(mat1)

array([[0.24672495, 0.01911702, 0.41950044],
       [2.31961994, 0.0548278 , 0.05482011],
       [2.49391312, 0.58895606, 0.2204062 ],
       [0.2943714 , 0.21475596, 0.2169042 ],
       [0.05854574, 3.66064129, 2.97534153]])

In [ ]:
# mat1의 제곱근 구하기
np.sqrt(mat1.astype('complex')) #nan = nat a number - 복소수 => .astype('complex') 추가해줌

array([[0.70477951+0.j        , 0.        +0.37183908j,
        0.80479099+0.j        ],
       [1.23411096+0.j        , 0.        +0.48389397j,
        0.        +0.48387701j],
       [1.25666734+0.j        , 0.87603352+0.j        ,
        0.        +0.68518201j],
       [0.73658675+0.j        , 0.        +0.68074789j,
        0.        +0.68244396j],
       [0.49189661+0.j        , 0.        +1.38321374j,
        0.        +1.31336127j]])

In [ ]:
# linear algebra functions
vec = np.array([1, 2, 3,])

# 1. norm
np.linalg.norm(vec)

# 2. eigenvalue
mat = np.array([[1, 0],
               [0, 1]])
np.linalg.eig(mat)

EigResult(eigenvalues=array([1., 1.]), eigenvectors=array([[1., 0.],
       [0., 1.]]))

### 2.2. Aggregation functions : 합계, 집계

In [ ]:
np.random.seed(0)
mat2 = np.random.rand(3, 2)
mat2

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [ ]:
# Summation
# axis=0 : 세로방향(=column 방향), axis=1 : 가로방향(row)
np.sum(mat2, axis=1) #axis 어떤 축을 기준으로 더하겠다. 0은 첫번째-세로방향-컬럼방향,1은 두번째-가로방향-row방향

array([1.26400287, 1.14764656, 1.06954891])

In [ ]:
# mean
np.mean(mat2, axis=0)

array([0.52507723, 0.63532222])

In [ ]:
# std
np.mean(mat2, axis=1)

array([0.63200144, 0.57382328, 0.53477446])

In [ ]:
# min, max
np.min(mat2)
np.min(mat2, axis=1)
mat2

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [ ]:
# 최소값이 있는 Index
np.argmin(mat2,axis=1)

array([0, 1, 0])

In [ ]:
# 최대값이 있는 Index
np.argmax(mat2,axis=0)

array([1, 0])

In [ ]:
# 그냥 정렬 (오름차순 정렬만 지원합니다)


In [ ]:
# index를 정렬


## 3. Performance Check

- Universal Function 기능을 통해 반복문을 사용한 것보다 훨씬 빠른 성능을 냅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [ ]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))

    for i in range(len(values)):
        output[i] = 1.0 / values[i]

    return output

In [ ]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array =

In [ ]:
%timeit reverse_num(big_array)

In [ ]:
%timeit 1.0 / big_array