# **STEP 11. 수치계산**

## **1. Numpy 기본 개념**

*   numpy 패키지 추가
*   패키지가 없는 경우, 설치 명령어 : pip install numpy



In [ ]:
# numpy 패키지 로드하여 np로 사용
import numpy as np

## **2. Numpy 배열**

### **2-1. 배열 예제**


In [ ]:
# 아래와 같은 데이터는 2개의 축을 가지며,
# 첫 번째 축은 길이가 2이고 두 번째 축은 길이가 3이다.
[[ 1, 0, 0],
 [ 0, 1, 2]]

[[1, 0, 0], [0, 1, 2]]

In [ ]:
# 아래와 같은 데이터는 1개의 축을 가지며,
# 축은 3가지 요소(element)를 가지고 있다고 하고 길이(length)는 3이다.
[1, 2, 1]

[1, 2, 1]

### **2-2. 배열 대표적인 속성값**

- ndarray.shape : 배열의 각 축(axis)의 크기
- ndarray.ndim : 축의 개수(Dimension)
- ndarray.dtype : 각 요소(Element)의 타입
- ndarray.itemsize : 각 요소(Element)의 타입의 bytes 크기
- ndarray.size : 전체 요소(Element)의 개수

In [ ]:
# a라는 변수에 (3, 4) 크기의 2D 배열을 생성해보자.
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# ndarray.shape : 배열의 각 축(axis)의 크기
print(a.shape)

(3, 4)


In [ ]:
# ndarray.dtype : 각 요소(Element)의 타입
print(a.dtype)

int64


In [ ]:
# ndarray.itemsize : 각 요소(Element)의 타입의 bytes 크기
print(a.itemsize)

8


In [ ]:
# ndarray.size : 전체 요소(Element)의 개수
print(a.size)

12


## **3. Numpy 배열 생성**

### **3-1. 배열 생성**

- np.array( )를 이용하여 Python에서 사용하는 Tuple(튜플)이나 List(리스트)를 입력으로 numpy.ndarray를 생성

In [ ]:
# numpy 패키지 로드하여 np로 사용
import numpy as np

In [ ]:
# a 배열 생성 & 타입 확인
a = np.array([2,3,4])
print(a)
print(a.dtype)

[2 3 4]
int64


In [ ]:
# b 배열 생성 & 타입 확인
b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)

[1.2 3.5 5.1]
float64


### **3-2. 다양한 차원의 배열 생성**

> * np.zeros(shape) : 0으로 구성된 N차원 배열 생성
> * np.ones(shape) : 1로 구성된 N차원 배열 생성
> * np.empty(shape) : 초기화되지 않은 N차원 배열 생성

In [ ]:
# (3,4) 크기의 배열을 생성하여 0으로 채움
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# (2,3,4) 크기의 배열을 생성하여 1로 채움
print(np.ones((2, 3, 4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
# 초기화 되지 않은 (2,3) 크기의 배열을 생성
print(np.empty((2, 3)))

[[5.06489711e-310 0.00000000e+000 1.23638216e-313]
 [6.99137997e-315 0.00000000e+000 6.56771733e-310]]


## **4. Numpy arange와 linspace 데이터 생성**

### **4-1. 연속적인 데이터 생성**

> - np.arange(): N 만큼 차이나는 숫자 생성
> - np.linspace(): N 등분한 숫자 생성


In [ ]:
# 10이상 30미만 까지 5씩 차이나게 생성
print(np.arange(10, 30, 5))

[10 15 20 25]


In [ ]:
# 0이상 2미만 까지 0.3씩 차이나게 생성
print(np.arange(0, 2, 0.3))

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [ ]:
# 0~99까지 100등분
x = np.linspace(0, 99, 100)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


### **4-2. arange와 linspace 차이점**

1) np.arange([start], stop, [step]..)
- [] 생략 가능
- 끝 값 포함 안 함
- 장점 : step, 범위를 구간, 간격 강조할 때 사용하면 코드 가독성 업!

2) np.linspace(start, stop, num=50..)
- 처음 값과 끝 값 포함
- 몇 개로 만들지 매개변수로 줌
- 장점 : 개수 강조할 때 사용하면 코드 가독성 업!


In [ ]:
# arange 함수는 끝 값을 포함하지 않기 때문에
# 가독성을 위해서 1.25를 1+0.25로 표현!
# 0부터 1.25 미만까지(끝 값 포함 안하니까 1까지 출력) 0.25씩 차이나게 생성
print(np.arange(0, 1+0.25, 0.25))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# 위와 동일한 결과를 linspace 함수를 이용하여 코딩
# 0부터 1까지(끝 값 포함) 5등분
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


## **5. Numpy 배열 출력**

- 1D와 2D 배열은 설명하지 않아도 어떻게 출력되는지 확인하실 수 있으나,
- 3D 배열은 2차원이 N개 출력되는 형식으로 나타남

In [ ]:
# 1차원 배열 출력
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
# 2차원 배열 출력
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# 3차원 배열 출력
# (3, 4)크기의 2차원 배열이 2개 출력되는 형식
c = np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## **6. Numpy 기본 연산**

### **6-1. element wise 연산**
* 차원(축)을 기준으로 행렬 내에서 같은 위치에 있는 원소끼리 연산을 하는 방식

In [ ]:
# a와 b 배열 생성하여 출력
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [ ]:
# a에서 b에 각각의 원소를 - 연산
c = a-b
print(c)

[20 29 38 47]


In [ ]:
# b 각각의 원소에 제곱 연산
print(b**2)

[0 1 4 9]


In [ ]:
# a 각각의 원소에 *10 연산
print(10*a)

[200 300 400 500]


In [ ]:
# a 각각의 원소가 35보다 작은지 Boolean 결과
print(a < 35 )

[ True  True False False]


### **6-2. 여러가지 곱셈**

- '*' : 각각의 원소끼리 곱셈 (Elementwise product, Hadamard product)
- '@' : 행렬 곱셈 (Matrix product)

In [ ]:
# A와 B 배열 생성하여 출력
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [ ]:
# A * B
# 각각의 원소끼리 곱셈
print(A * B)

[[2 0]
 [0 4]]


In [ ]:
# A @ B
# 행렬 곱셈 사용
print(A @ B)

[[5 4]
 [3 4]]


### **6-3. 자동 형 변환**
- 수치연산 진행할 때 각각의 .dtype이 다르면,
- 타입이 큰쪽(int < float < complex)으로 자동으로 변경

In [ ]:
# a와 b 배열 생성 & 타입 확인
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi,3)

print(a)
print(b)
print(a.dtype)
print(b.dtype)

[1 1 1]
[0.         1.57079633 3.14159265]
int32
float64


In [ ]:
# a(int), b(float) 연산 시 float로 upcasting
c = a + b
print(c)
print(c.dtype)

[1.         2.57079633 4.14159265]
float64


In [ ]:
# 마찬가지로 복소수 연산 시 complex(복소수)로 upcasting
# exp 함수는 지수 함수
d = np.exp(c*1j)
print(d)
print(d.dtype)

[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
complex128


### **6-4. 집계함수**

- .sum( ) : 모든 요소의 합
- .min( ) : 모든 요소 중 최소값
- .max( ) : 모든 요소 중 최대값
- .argmax( ) : 모든 요소 중 최대값의 인덱스
- .cumsum( ) : 모든 요소의 누적합

In [ ]:
# a 배열 생성 & 출력
# 0부터 8미만까지 출력하고 (2,4) 크기로 재가공하고 제곱하여 출력
a = np.arange(8).reshape(2, 4)**2
print(a)

[[ 0  1  4  9]
 [16 25 36 49]]


In [ ]:
# 모든 요소의 합
print(a)
print(a.sum())

[[ 0  1  4  9]
 [16 25 36 49]]
140


In [ ]:
# 모든 요소 중 최소값
print(a.min())

0


In [ ]:
# 모든 요소 중 최대값
print(a.max())

49


In [ ]:
# 모든 요소 중 최대값의 인덱스
print(a)
print(a.argmax())

[[ 0  1  4  9]
 [16 25 36 49]]
7


In [ ]:
# 모든 요소의 누적합
# 14 = 0 + 1 + 4 + 9
print(a)
print(a.cumsum())

[[ 0  1  4  9]
 [16 25 36 49]]
[  0   1   5  14  30  55  91 140]


### **6-5. 집계함수 axis 값을 매개변수로 입력**
- .sum( ), .min( ), .max( ), .cumsum( )과 같은 연산에 axis 값을 입력하면, 축을 기준으로도 연산 가능
- axis = 0 (열 기준)
- axis = 1 (행 기준)

In [ ]:
# b 배열 생성 & 출력
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# axis = 0은 열 기준으로 연산
print(b.sum(axis=0))

[12 15 18 21]


In [ ]:
# axis = 1은 행 기준으로 연산
print(b.sum(axis=1))

[ 6 22 38]


## **7. Numpy 범용 함수**

- 수학적인 연산이 너무 많기 때문에 .sqrt( )만 예시로 실습 진행
- 필요한 범용 함수는 [available-ufuncs](https://numpy.org/doc/1.18/reference/ufuncs.html#available-ufuncs)를 확인!

In [ ]:
# B 배열 생성 & 출력
B = np.array([1, 4, 9])
print(B)

[1 4 9]


In [ ]:
# y = sqrt(x)
# sqrt는 제곱근 계산
print(np.sqrt(B))

[1. 2. 3.]


## **8. Numpy 인덱싱과 슬라이싱**
- 인덱싱(Indexing, 가리킴)과 슬라이싱(Slicing, 잘라냄)은 각각 문자열에서 한개 또는 여러개를 가리켜서 그 값을 가져오거나 뽑아내는 방법

### **8-1. 인덱싱과 슬라이싱**

- Numpy에서 인덱싱과 슬라이싱에 대한 개념은 Python과 기본적으로 동일

In [ ]:
# a 배열 생성 & 출력
a = np.arange(10)**2
print(a)

[ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
# a 배열의 2번째 인덱스 출력
print(a[2])

4


In [ ]:
# a 배열의 2~4번 인덱스 출력
print(a[2:5])

[ 4  9 16]


In [ ]:
# reverse : 배열의 요소 거꾸로 출력
print(a[ : :-1])

[81 64 49 36 25 16  9  4  1  0]


In [ ]:
# 0~5번에서 2Step 인덱스 출력
# a[0:6:2] = a[:6:2]
# 인덱스 0, 2, 4 해당하는 값에 1000 삽입
a[0:6:2] = 1000
print(a)

[1000    1 1000    9 1000   25   36   49   64   81]


### **8-2. 인덱스 배열로 인덱싱**
- 인덱스를 가진 배열로 인덱싱 진행

In [ ]:
# a 배열 생성 & 출력
a = np.arange(8)**2
print(a)

[ 0  1  4  9 16 25 36 49]


In [ ]:
# i 1차원 배열 생성 & 출력
# a 배열의 index로 i를 삽입하여 출력
i = np.array([1, 1, 3, 5])
print(a[i])

[ 1  1  9 25]


In [ ]:
# j 2차원 배열 생성
# a 배열의 index로 j를 삽입하여 출력
j = np.array([[3, 4], [2, 5]])
print(a[j])

[[ 9 16]
 [ 4 25]]


### **8-3. boolean 인덱싱**
- Boolean 타입을 가진 값들로 인덱싱 진행

In [ ]:
# a 배열 생성 & 출력
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# b는 a > 4 조건이 적용된 Boolean 값이 든 배열
b = a > 4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [ ]:
# Boolean 값이 든 b 배열을 a 배열의 index로 삽입
# True인 값들만 출력
print(a[b])
a[b].shape

[ 5  6  7  8  9 10 11]


(7,)

In [ ]:
# a[b]에 해당하는 애들만 0 삽입하여 a 출력
a[b] = 0
print(a)

[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


## **9. Numpy 크기 변경**
- .ravel : 1차원으로 변경
- .reshape : 지정한 차원으로 변경
- .T : 전치(Transpose) 변환

In [ ]:
# a 배열 생성 & shape 출력
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
# .ravel : 모든 원소를 1차원으로 변경
print(a.ravel())
print(a.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# .reshape : 지정한 차원으로 변경
# [3,4] => [2,6]로 변경
print(a.reshape(2, 6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# .T : [3,4]의 전치(transpose)변환으로 [4,3] 출력
print(a.T)
print(a.T.shape)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [ ]:
# 만약 전치 형태로 a 배열에 저장하고 싶다면!
a = a.T
print(a)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## **10. Numpy 데이터 합치기**
- np.vstack() 와 np.hstack()를 통해 데이터를 합치기
- np.vstack(): axis=0(열) 기준으로 쌓음
- np.hstack(): axis=1(행) 기준으로 쌓음

In [ ]:
# a 배열 생성 & 출력
a = np.array([1, 2, 3, 4]).reshape(2, 2)
print(a)

[[1 2]
 [3 4]]


In [ ]:
# b 배열 생성 & 출력
b = np.array([5, 6, 7, 8]).reshape(2, 2)
print(b)

[[5 6]
 [7 8]]


In [ ]:
# [2,2] => [4,2]
# np.vstack(): axis=0(열) 기준으로 쌓음
print(np.vstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# [2,2] => [2,4]
# np.hstack(): axis=1(행) 기준으로 쌓음
print(np.hstack((a,b)))

[[1 2 5 6]
 [3 4 7 8]]


## **11. Numpy 데이터 쪼개기**

- np.hsplit( )을 통해 숫자1개가 들어갈 경우, X개로 등분
- np.hsplit( )을 통해 리스트로 넣을 경우, axis=1 기준 인덱스로 데이터를 분할

In [ ]:
# a 배열 생성 & 출력
a = np.arange(12).reshape(2, 6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
# [2,6] => [2,2] 데이터 3개로 등분
print(np.hsplit(a, 3))

[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]


In [ ]:
# [2,6] => [:, :3], [:, 3:4], [:, 4:]로 분할
# a를 3번째 열 ~ 4번째 열 미만 기준으로 분할하여 3개의 array를 반환
print(a)
print(np.hsplit(a, (3,4)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[array([[0, 1, 2],
       [6, 7, 8]]), array([[3],
       [9]]), array([[ 4,  5],
       [10, 11]])]


# **자기 주도 학습 - 문제**


## **1. Numpy 문제 (1)**

* Numpy 선언



In [ ]:
# 1) numpy 패키지 로드하여 np로 사용
import numpy as np

## **2. Numpy 문제 (2)**

* 리스트로 배열 만들기



In [ ]:
# 1) pythonList 변수에 리스트 선언하기 (리스트 요소는 자유롭게 구성)
# 2) npArray 변수에 pythonList 변수를 통해 Numpy 배열 선언
# 3) 각각 pythonList, npArray 변수 출력
pythonList = [1, 1.5, "python"]
npArray = np.array(pythonList)
print(pythonList)
print(npArray)

[1, 1.5, 'python']
['1' '1.5' 'python']


## **3. Numpy 문제 (3)**

* 0으로 구성된 2차원 배열 생성



In [ ]:
# 1) 0이 10개 채워진 1차원 배열 생성하여 출력
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 2) 0이 10개 채워진 (5,5) 형태의 2차원 배열 생성하여 출력
print(np.zeros((5, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## **4. Numpy 문제 (4)**

* arange & linspace 함수를 사용하여 배열 생성



In [ ]:
# 1) [0.  0.5  1. ]
# 2) arange 함수를 사용하여 (1)과 동일한 결과 나오게끔 배열 생성하여 출력
# 0이상 1.05미만, 0.5씩 차이나게 구현 (코드 가독성을 위해 1+0.5로 코딩)
print(np.arange(0, 1+0.5, 0.5))

[0.  0.5 1. ]


In [ ]:
# 3) linspace 함수를 사용하여 (1)과 동일한 결과 나오게끔 배열 생성하여 출력
print(np.linspace(0, 1, 3))

[0.  0.5 1. ]


## **5. Numpy 문제 (5)**

* 인덱싱(Indexing, 가리킴)과 슬라이싱(Slicing, 잘라냄) 이해



In [ ]:
python = np.arange(10)**3
print(python)

[  0   1   8  27  64 125 216 343 512 729]


In [ ]:
# 1) python 배열의 2번째 인덱스 출력
print(python[2])

8


In [ ]:
# 2) python 배열의 3~5번 인덱스 출력
print(python[3:6])

[ 27  64 125]


In [ ]:
# 3) python 배열의 64이상의 요소만 출력
python_64 = python > 64
print(python[python_64])

print(python[python > 64])

[125 216 343 512 729]
[125 216 343 512 729]


## **6. Numpy 문제 (6)**

* 데이터 합치기 & 쪼개기



In [ ]:
python_1 = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(python_1)

[[1 2 3]
 [4 5 6]]


In [ ]:
python_2 = np.array([7, 8, 9, 10, 11, 12]).reshape(2, 3)
print(python_2)

[[ 7  8  9]
 [10 11 12]]


In [ ]:
# 1) 열을 기준으로 데이터 합쳐서 출력
# np.vstack(): axis=0(열) 기준으로 쌓음
print(np.vstack((python_1, python_2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# 2) 행을 기준으로 데이터 합쳐서 출력
# np.hstack(): axis=1(행) 기준으로 쌓음
print(np.hstack((python_1, python_2)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# 3) python_1 변수에 열을 기준으로 3등분 쪼개어 출력
# [2,3] => [2,1] 데이터 3개로 등분
print(np.hsplit(python_1, 3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [ ]:
# 4) python_1 변수에 행을 기준으로 2등분 쪼개어 출력
# [2,3] => [1,3] 데이터 2개로 등분
print(np.vsplit(python_1, 2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]
